# -*- coding: utf-8 -*-
"""Foodtrack.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Zdyvh0UNevNyT-gzUor8VG4hYMP4s-Pm

# Исполнитель: Преснякова Анастасия, группа 20 БИ-2

Проект: сеть фудтраков
"""

!ln -fs /usr/share/zoneinfo/Europe/Moscow /etc/localtime
!date

"""# Связь с диском. Отображение содержания папок."""

from google.colab import auth
auth.authenticate_user()
!pip install --upgrade gspread
import gspread
from google.colab import drive
drive.mount('/content/drive')
import os
print(os.getcwd())
print(os.listdir('./'))
print(os.listdir('/content/drive/MyDrive/SWOT'))
from oauth2client.client import GoogleCredentials
gc = gspread.authorize(GoogleCredentials.get_application_default())
table = gc.open_by_key('10JBh5Ueoyor2ALXHKuSSjAKgWj2EPTY-cVqVfN06kRQ')
print(table.worksheets())
print(dir(table))

"""# Strengths"""

import matplotlib.pyplot as plt
import matplotlib

worksheet = table.worksheet("Strengths")
rows = worksheet.get_all_values()
#print(rows)
name = list()
price = list()
count = list()
value = list()
i=0
for row in rows:
  if(i>0):
    print (i, row)
    name.append(row[0])
    value.append(int(row[2])*float(row[3]))
  i+=1
strengths = sum(value)
print('Мощность:')
for i in range(0,len(rows)-1,1):
   print(name[i],':',value[i])

print('Общая мощность сильных сторон: ', strengths)

title = [ "1", "2", "3", "4", "5"]
x=title
x_float = [1, 2, 3, 4, 5]
y = value
fig=plt.figure(figsize=(8,6), dpi=72)
plt.bar(x_float, y, width=0.75, align='edge', alpha=0.4)
plt.xticks(x_float,  x_float, fontsize=14)
plt.xlabel('Обозначения', fontsize=14)
plt.ylabel('Мощность', fontsize=14)
plt.title('Strengths', fontsize=14)
plt.grid(True, color='r', linestyle='-', linewidth=2)
#plt.draw()
plt.show()

for i in range(name.__len__()):
        print(i+1, " - ", name[i], "; ")
        i += 1

"""# Weaknesses"""

worksheet = table.worksheet("Weaknesses")
rows = worksheet.get_all_values()
#print(rows)
name = list()
price = list()
count = list()
value = list()
i=0
for row in rows:
  if(i>0):
    print (i, row)
    name.append(row[0])
    value.append(int(row[2])*float(row[3]))
  i+=1
weaknesses = sum(value)
print('Мощность:')
for i in range(0,len(rows)-1,1):
   print(name[i],':',value[i])

print('Общая мощность слабых сторон: ', weaknesses)

title = [ "1", "2", "3", "4"]
x=title
x_float = [1, 2, 3, 4]
y = value
fig=plt.figure(figsize=(8,6), dpi=72)
plt.bar(x_float, y, width=0.75, align='edge', alpha=0.4)
plt.xticks(x_float,  x_float, fontsize=14)
plt.xlabel('Обозначения', fontsize=14)
plt.ylabel('Мощность', fontsize=14)
plt.title('Weaknesses', fontsize=14)
plt.grid(True, color='r', linestyle='-', linewidth=2)
#plt.draw()
plt.show()

for i in range(name.__len__()):
        print(i+1, " - ", name[i], "; ")
        i += 1

"""# Opportunities"""

worksheet = table.worksheet("Opportunities")
rows = worksheet.get_all_values()
#print(rows)
name = list()
price = list()
count = list()
value = list()
i=0
for row in rows:
  if(i>0):
    print (i, row)
    name.append(row[0])
    value.append(int(row[2])*float(row[3]))
  i+=1
opportunities = sum(value)
print('Мощность:')
for i in range(0,len(rows)-1,1):
   print(name[i],':',value[i])

print('Общая мощность возможностей: ', opportunities)

title = [ "1", "2", "3", "4"]
x=title
x_float = [1, 2, 3, 4]
y = value
fig=plt.figure(figsize=(8,6), dpi=72)
plt.bar(x_float, y, width=0.75, align='edge', alpha=0.4)
plt.xticks(x_float,  x_float, fontsize=14)
plt.xlabel('Обозначения', fontsize=14)
plt.ylabel('Мощность', fontsize=14)
plt.title('Opportunities', fontsize=14)
plt.grid(True, color='r', linestyle='-', linewidth=2)
#plt.draw()
plt.show()

for i in range(name.__len__()):
        print(i+1, " - ", name[i], "; ")
        i += 1

"""# Threats"""

worksheet = table.worksheet("Threats")
rows = worksheet.get_all_values()
#print(rows)
name = list()
price = list()
count = list()
value = list()
i=0
for row in rows:
  if(i>0):
    print (i, row)
    name.append(row[0])
    value.append(int(row[2])*float(row[3]))
  i+=1
threats = sum(value)
print('Мощность:')
for i in range(0,len(rows)-1,1):
   print(name[i],':',value[i])

print('Общая мощность угроз: ', threats)

title = [ "1", "2", "3", "4"]
x=title
x_float = [1, 2, 3, 4]
y = value
fig=plt.figure(figsize=(8,6), dpi=72)
plt.bar(x_float, y, width=0.75, align='edge', alpha=0.4)
plt.xticks(x_float,  x_float, fontsize=14)
plt.xlabel('Обозначения', fontsize=14)
plt.ylabel('Мощность', fontsize=14)
plt.title('Threats', fontsize=14)
plt.grid(True, color='r', linestyle='-', linewidth=2)
#plt.draw()
plt.show()

for i in range(name.__len__()):
        print(i+1, " - ", name[i], "; ")
        i += 1

"""# SWOT

"""

result = float
result = strengths + (-1)*weaknesses + opportunities + (-1)*threats
title = [ "Strengths", "Weaknesses", "Opportunities", "Threats", "Result"]
x=title
x_float = [1, 2, 3, 4, 5]
y = [strengths, (-1)*weaknesses, opportunities, (-1)*threats, result]
fig=plt.figure(figsize=(8,6), dpi=72)
plt.bar(x_float, y, width=0.75, align='edge', alpha=0.4)
plt.xticks(x_float,  x_float, fontsize=14)
plt.xlabel('Обозначения', fontsize=14)
plt.ylabel('Мощность', fontsize=14)
plt.title('SWOT', fontsize=14)
plt.grid(True, color='r', linestyle='-', linewidth=2)
#plt.draw()
plt.show()
for i in range(title.__len__()):
        print(i+1, " - ", title[i], "; ")
        i += 1
print('SWOT общий результат: ', result)
dif = float
dif = (strengths + opportunities)/(strengths + weaknesses + opportunities + threats)
print('Результирующая вероятность: ', dif)